### ISSUE TITLE
Installation issues with Python 2.7 on Linux

### ISSUE THREAD

**Issue by rth** [FreeDiscovery/FreeDiscovery#42]
Issue submitted by @mossaab0,
> I'm trying to install the tools, and am facing the following issues:
> 
> 1.a. Installing FreeDiscovery on my existing Python 2.7 environment, I encountered these two problems 'No module named pandas' and 'No module named nltk.stem.porter'. They were easily solved by installing pandas and nltk using pip. Buy you might wanna consider adding them to the installation script.
> 
> 1.b. The test suit fails after passing 39 tests and skipping 6 (log attached). It doesn't look to me that this is related to my choice of Py2.7. But if you think otherwise, I'll install Py3, and see what happens.
>  2. I have not used docker before, and it seems to need some root privileges. I have not yet talked to out sysadmins, but my expectation is that they can install it on my desktop, but probably not on our cluster of servers. Can I, instead, get a list of the software it includes, so that I compile them, without root privileges, to make them runnable from the cluster? All of this is assuming that the experiments need to be distributed over several machines for fast throughput.
> [cf. list of failed tests [freediscovery-tests.txt](https://github.com/FreeDiscovery/FreeDiscovery/files/673187/freediscovery-tests.txt)]

**Comment by rth** [comment]
Thanks a lot for the feedback, @mossaab0 !

1. As far I understand you were installing FreeDiscovery with your system python, right? The issue is likely that your python environment doesn't have the same version of dependencies (e.g. numpy etc) as those required by FreeDiscovery. For this reason I would strongly recommend using a python virtual environment (which would also help to ensure reproducibility of results between your computer and the calculations on the cluster). Two approaches are possible,
   1. Using Minconda, as described in [the installation instructions](https://freediscovery.github.io/doc/dev/installation_instructions.html#a-python-install), which would create a miniconda folder in your `$HOME`, create a virtual environment and install all the dependencies there. It does not requires root access, and can also be used to install non python packages such as gcc, git etc. It also makes switching between Py2.7 and PY3.x easier. 
   2. Alternatively, using the [standard  python virtualenv](https://virtualenv.pypa.io/en/stable/userguide/) is also possible, which would consist in, something along the lines of,
       
           virtualenv fd-env  # creating the virtual env
           source activate fd-env # activating virtualenv
           pip install -r build_tools/requirements_conda.txt
           pip install -r build_tools/requirements_pip_unix.txt
       
       the last two lines install the right versions of the dependencies (including pandas and nltk), currently running `python setup.py install` doesn't actually install any dependencies. 

   Also note that currently the installation requires gcc 4.8 on Linux to compile simhash-py (for duplicates detection), but if you are not using that functionality, even if the compilation fails with earlier version of gcc, the rest of FreeDiscovery should work (and all tests should pass or be skipped).  I would recommend option i. with Python 3.5 if possible. 

 2. Sorry if the docs are not clear enough about that. Docker (which does require root access) is an alternative method of deployment, so it's either a) install this package with Python b) or just download / build the Docker image and use that (even if Python is not installed). I think in your use case, just installing FreeDiscovery with Python would be better (as it's more suitable for parallel runs on a server), in which case you don't need Docker at all.

Please let me know if this works, and don't hesitate to open issues if you find other things that could be improved..

**Comment by mossaab0** [comment]
I have just tried `1.i`. I had to manually `pip install` each of the following: `pytest`, `numpy`, `sklearn` and `scipy`, before I faced the issue reported earlier. I think the reason is that I already had these packages installed in my existing Anaconda 2.7 environment. But for some reason, they don't get automatically installed through the process described in the guidelines (with Miniconda for Python 3.5).

Subsequently, I installed `pandas` and `nltk`. It looks like now I'm getting the expected output:
`====== 159 passed, 9 skipped in 33.75 seconds =======`

**Comment by DenisFLASH** [comment]
Hi @mossaab0 
I had some similar issues on installing/rebuilding FD. 
At the time, there was `conda-setup.sh` but I was doing my tests on Windows, so i created the same script in `.bat` format.  Now i never have installation and packaging issues, as this script will do everything for me:

- delete the previous version of FreeDiscivery virtualenv

- re-create FreeDiscovery virtualenv from scratch with Python 3.5 version

- install all needed packages 

- import and run unit tests

So now each time i wanna rebuild a project, i just run `conda_setup.bat` and it does all for me.  If you're under Linux (which I think is the case), then `conda_setup.sh` is perfectly fine for you. The good news is that not only it will automate your installation, but also will never mess up with your existing system Python 2.7 (which is otherwise quite uncomfortable, as there are some side effects each time you install something manually).

Hope this helps

**Comment by rth** [comment]
This issue has been resolved since, closing it as fixed.
