### ISSUE TITLE
Comments about FreeDiscovery

### ISSUE THREAD

**Issue by kanecm** [FreeDiscovery/FreeDiscovery#53]
executing: bash conda_run.sh

(freediscovery-env) christopher@christopher-HP-Pavilion-17-Notebook-PC:~/FreeDiscovery$ bash conda_run.sh

Starting FREEDiscovery Server  '0.8.dev0' (Fri Jan 13 19:07:26 EST 2017)
    shared folder set to /home/christopher/freediscovery_shared/
 
Traceback (most recent call last):
  File "scripts/run_api.py", line 9, in <module>
    from freediscovery.server import fd_app
  File "/home/christopher/FreeDiscovery/freediscovery/server/__init__.py", line 7, in <module>
    from .app import fd_app
  File "/home/christopher/FreeDiscovery/freediscovery/server/app.py", line 10, in <module>
    from flask_restful import Api, Resource
ImportError: No module named 'flask_restful'
(freediscovery-env) christopher@christopher-HP-Pavilion-17-Notebook-PC:~/FreeDiscovery$

**Comment by rth** [comment]
@kanecm This sounds like the `flask_restful` package was not installed for some reason. It should be fixed by running the two lines below from the `FreeDiscovery` folder,
```bash
source activate freediscovery-env
pip install -r build_tools/requirements_pip.txt 
```
that are part of the [installation instructions](https://freediscovery.github.io/doc/dev/installation_instructions.html#a-python-install) but there may have been some mixup if you started with the outdated version of the instructions first (issue #52). Please let me know if this fixed it...

**Comment by kanecm** [comment]
Roman,
Starting FREEDiscovery Server  '0.8.dev0' (Sun Jan 15 09:43:25 EST 2017)
    shared folder set to /home/christopher/freediscovery_shared/
 
 * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)


So: source activate freediscovery-env
pip install -r build_tools/requirements_pip.txt worked.
should that be added to the directions?

Now that I have it running, I need to figure out how it works.

Sincerely, 
Christopher Kane 703-727-9493

**Comment by rth** [comment]
@kanecm Great that it is working!Those steps are already included in the [installation instructions](https://freediscovery.github.io/doc/dev/installation_instructions.html#a-python-install) (step 2.a.3),  but I think the issue was that you started the install with outdated instructions hence this issue. 
Making it as closed, feel free to reopen it if needed..

**Comment by kanecm** [comment]
Examples
The examples of use for FreeDiscovery can be found in the FreeDiscovery_examples.zip attached. 
"Attached" where?

Sincerely, 
Christopher Kane 703-727-9493

**Comment by rth** [comment]
@kanecm Thanks a lot for testing this! Where was this sentence written? If it was in some earlier email from me, it should be considered outdated, and the current version of the documentation can be found at,
 *  https://freediscovery.github.io/doc/dev (developpement version, it automatically gets updated with changes in the code)

and the examples are located at,
  *  https://freediscovery.github.io/doc/dev/examples/index.html  (individual ones are accessible by clicking on the corresponding link)  

Sorry about the confusion. Thanks again, and if you encounter any other issue, please let me know..

**Comment by rth** [comment]
@kanecm Also,  significant code reogranisation was done in pull request #57, so please make sure you are using the latest development version. `git pull` in the `FreeDiscovery` folder should be sufficient to synchronize it. Thanks!

**Comment by kanecm** [comment]
Roman,
Found:
     The examples of use for FreeDiscovery can be found in the FreeDiscovery_examples.zip attached.

on page:

Examples — FreeDiscovery 0.5.0 documentation
  
|  
|   |  
Examples — FreeDiscovery 0.5.0 documentation
   |  |

  |

 

Sincerely, 
Christopher Kane 703-727-9493

**Comment by kanecm** [comment]
Roman,
Style change:

In addition, FreeDiscovery can be used as Python package and aims to expose a scikit-learn compatible API. ->In addition, FreeDiscovery can be used as a Python package and aims to expose a scikit-learn compatible API.
on Page: FreeDiscovery — FreeDiscovery 0.8.dev0 documentation

  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
FreeDiscovery — FreeDiscovery 0.8.dev0 documentation
   |   |

  |

  |

 

Sincerely, 
Christopher Kane 703-727-9493

**Comment by kanecm** [comment]
Roman,
On clicking: Examples — FreeDiscovery 0.8.dev0 documentation

  
|  
|   |  
Examples — FreeDiscovery 0.8.dev0 documentation
   |  |

  |

 
 Then copying: python examples/categorization_example.py to my terminal and executing I get:
(freediscovery-env) christopher@christopher-HP-Pavilion-17-Notebook-PC:~/FreeDiscovery$ python examples/categorization_example.py
python: can't open file 'examples/categorization_example.py': [Errno 2] No such file or directory

Checking:
(freediscovery-env) christopher@christopher-HP-Pavilion-17-Notebook-PC:~/FreeDiscovery/examples$ ls
python_categorization.py  README.txt              REST_clustering.py           REST_email_threading.py 
python_clustering.py      REST_categorization.py  REST_duplicate_detection.py
(freediscovery-env) christopher@christopher-HP-Pavilion-17-Notebook-PC:~/FreeDiscovery/examples$ 


Sincerely, 
Christopher Kane 703-727-9493

**Comment by rth** [comment]
> The examples of use for FreeDiscovery can be found in the FreeDiscovery_examples.zip attached. on page:
> Examples — FreeDiscovery 0.5.0 documentation

OK, but what's the URL of that page? It's really outdated, the current dev verison is 0.8 and stable 0.7 )

> Style change: In addition, FreeDiscovery can be used as Python package and aims to expose a scikit-learn compatible API. ->In addition, FreeDiscovery can be used as a Python package and aims to expose a scikit-learn compatible API.

How would you feel about doing a Pull Request with all the style changes you would like to make, as described in the  ["Contributing" section](https://freediscovery.github.io/doc/dev/contributing.html#contributing)?

>   Then copying: python examples/categorization_example.py to my terminal and executing I get: (freediscovery-env) christopher@christopher-HP-Pavilion-17-Notebook-PC:~/FreeDiscovery$ python examples/categorization_example.py python: can't open file 'examples/categorization_example.py': [Errno 2] No such file or directory

Yes, you are right the examples were renamed in the last update, but I missed that line it the docs, it should have been,
```py
python examples/REST_categorization.py
```
a Pull Request to fix this would be welcome )

Also would you mind responding on the github page of this issue https://github.com/FreeDiscovery/FreeDiscovery/issues/53 instead of by email, because for some reason github doesn't seem parse correctly the email response. Thanks again for all the feedback!

**Comment by rth** [comment]
Aww, yes, indeed, what happened is that 
 * https://freediscovery.github.io/doc/dev/ -  is the right version of the docs (version 0.8)
 * https://freediscovery.github.io/docs/dev/  (docs with an "s") had a very outdated version of the docs (version 0.5) 

I now removed the second URL completely which should fix it. Thanks a lot for reporting this subtle issue!

**Comment by kanecm** [comment]
Roman,
Working it.
On page:

Examples — FreeDiscovery 0.8.dev0 documentation
  
|  
|   |  
Examples — FreeDiscovery 0.8.dev0 documentation
   |  |

  |

 
 python examples/categorization_example.py -> 
python examples/python_categorization.py
There is more than one.

Sincerely, 
Christopher Kane 703-727-9493

**Comment by rth** [comment]
Closing this as fixed. Thanks again for your feedback @kanecm !
